### ISSUE TITLE
Explore->Info - "Log to save"

### ISSUE THREAD

**Issue by ewilloughby** [emory-libraries-ecds/ATLMaps-Ember#18]
Change to "Log in to save"

**Comment by jayvarner** [comment]
@ewilloughby here is where you can find this in the code: [https://github.com/ecds/ATLMaps-Client/blob/develop/app/templates/components/project-pane.hbs#L10](https://github.com/ecds/ATLMaps-Client/blob/develop/app/templates/components/project-pane.hbs#L10)

**Comment by jayvarner** [comment]
Eric took care of this...about to push.
