### ISSUE TITLE
atlmaps.org/admin/data/new = error page

### ISSUE THREAD

**Issue by AshleyCheyemi** [emory-libraries-ecds/ATLMaps-Ember#25]
I think I broke the tool, using it too much. Sorry.

**Comment by jayvarner** [comment]
@AshleyCheyemi I resolved this by removing the filter that was set on `Religious Sounds: Hindu/Muslim`. Lets just skip filters for now :)

**Comment by AshleyCheyemi** [comment]
Will do! Didn't even realize I selected a filter...must have been clicking away too fast. Thank you!
