### ISSUE TITLE
HOLC layer in explore weird description

### ISSUE THREAD

**Issue by AshleyCheyemi** [emory-libraries-ecds/ATLMaps-Ember#26]
![screen shot 2017-08-31 at 6 39 21 pm](https://user-images.githubusercontent.com/29981780/29948311-2538f6bc-8e7c-11e7-82f7-53a174c6ce85.png)

**Comment by jayvarner** [comment]
<img width="664" alt="explore__atlmaps_and_build_a_restful_json_api_with_rails_5_-_part_one_ _scotch" src="https://user-images.githubusercontent.com/24685/30094988-d33e990e-929d-11e7-83b7-7789a9b8c088.png">
