### ISSUE TITLE
Cannot access 3rd page of data 

### ISSUE THREAD

**Issue by AshleyCheyemi** [emory-libraries-ecds/ATLMaps-Ember#28]
Explore --> Data (30 layers) --> will not load 3rd page

**Comment by jayvarner** [comment]
This is caused by invalid data being allowed through. There is a fix in the next push, probably tonight, of the back end.

**Comment by AshleyCheyemi** [comment]
Ok, thanks, Jay. Is there specific data that I tried to load that was invalid/bad? In other words, how do I not mess this up going forward?

**Comment by jayvarner** [comment]
though all the results show, i'm leaving this open because there is a conflict with an edge case. i'll close the ticket once that is done.
