### ISSUE TITLE
XLS layer creation tool malfunction 

### ISSUE THREAD

**Issue by AshleyCheyemi** [emory-libraries-ecds/ATLMaps-Ember#36]
@ewilloughby @jayvarner  

1. When I try to upload an XLS, I get this pop-up box:

![screen shot 2017-11-09 at 11 25 35 am](https://user-images.githubusercontent.com/29981780/32616680-f0bd678c-c540-11e7-8e15-64139bfca6f5.png)

Here is the XLS file that I'm trying to upload through the tool: 
[TransitStops.xlsx](https://github.com/ecds/ATLMaps-Client/files/1458391/TransitStops.xlsx)

NOTE: I am downloading these XLS files from Google drive...perhaps this has something to do with it being incompatible with the tool? I've played around with switching between .xls and .xlsx but to no avail. Perhaps an issue of too many points?

2. This XLS gets made, but it does not show points. Rather, there is a polygon symbol and no map info created:
[Solid Waste In MetroATL.xlsx](https://github.com/ecds/ATLMaps-Client/files/1458432/Solid.Waste.In.MetroATL.xlsx)

![screen shot 2017-11-09 at 11 47 48 am](https://user-images.githubusercontent.com/29981780/32617853-1fe73d96-c544-11e7-9d67-69009ba87459.png)

**Comment by jayvarner** [comment]
Fixed by [This commit on the addon](https://github.com/Atlanta-Explorer/ember-cli-excel2geojson/commit/8e898652b683bb9e07025f97e1c9e250fa8eb348).
