### ISSUE TITLE
Blank box after project creation

### ISSUE THREAD

**Issue by AshleyCheyemi** [emory-libraries-ecds/ATLMaps-Ember#5]
When I'm logged in, go to Projects, select my "Buford Maps" project, this appears, which I'm not sure what it's supposed to do and when I click Explore Project at bottom of box, nothing happens:
![screen shot 2017-07-14 at 9 36 55 am](https://user-images.githubusercontent.com/29981780/28214453-4708f744-6878-11e7-9b11-2c529e569e7b.png)

**Comment by jayvarner** [comment]
Fixed by 4e5314b
